Adding Elephant And Giraffe classes and their requirements in AnimalF…
rkoychev/Animal_Kingdom_2024 pull request #15
Opened 2024-08-14 00:04 UTC by Kamen06

…amily. Fixing give birth method since elephants and giraffes give birth differenrly from other mammals

2024-08-14 08:29 UTC, teodora1203 requested changes

2024-08-14 09:39 UTC, rkoychev requested changes

2024-08-14 10:09 UTC, Kamen06 commented on src/AnimalFamily/AnimalFamily.ts
> +          ...GIRAFFE_FAMILY_REQUIREMENTS,
It was formated in my IDE. It still is. I don't know what happened.

2024-08-14 10:28 UTC, Kamen06 commented on src/animals/Elephant.ts
> +        const candidateElephants: AnimalCandidate[] = super.giveBirth(1) as AnimalCandidate[];
OK, but in the document it is stated that elephants can have only one child. That's why I hardcoded it. Is it ok if i hardcode it but extract it into a constant first?

2024-08-14 10:39 UTC, Kamen06 commented on src/animals/Elephant.ts
> +            const babyElephantWeight = Math.round((Math.random() * (75 - 65) + 65));
Height of a giraffe isn't the same as elephant's. With this code, both the weight and the height are randomly generated. Height is between 0.8m and 1.2m. Weight is between 65kg and 75kg. I looked the info in the net

2024-08-14 11:06 UTC, Kamen06 commented on src/AnimalFamily/AnimalFamily.ts
>        break;
it will throw error since other animals property canHaveFamily = false, therefore the validations will catch the problem

2024-08-14 11:16 UTC, Kamen06 commented on src/animals/Lion.ts
> +    throw new Error("Method not implemented.");
got tired

2024-08-14 11:18 UTC, Kamen06 commented on src/animals/Giraffe.ts
> +            const babyGiraffeHeight = Math.round((Math.random() * (1.8 - 1.5) + 1.5) * 100) / 100;
that is a way to set a random height between 1.5 and 1.8 meters

2024-08-14 11:38 UTC, teodora1203 commented on src/animals/Elephant.ts
> +        const candidateElephants: AnimalCandidate[] = super.giveBirth(1) as AnimalCandidate[];
yes that's what I meant

2024-08-14 11:47 UTC, teodora1203 commented on src/animals/Elephant.ts
> +            const babyElephantWeight = Math.round((Math.random() * (75 - 65) + 65));
i get that giraffes and elephants don't have the same measurements, that's the magic of reusable functions. What I meant is you can have a function `getRandomMeasurement(min: number, max: number)` and call it with the appropriate min and max values (you should extract them in constants too)

2024-08-14 12:24 UTC, rkoychev commented on src/animals/Giraffe.ts
> +            const babyGiraffeHeight = Math.round((Math.random() * (1.8 - 1.5) + 1.5) * 100) / 100;
extract in constants

2024-08-15 09:51 UTC, rkoychev approved these changes

2024-08-15 09:51 UTC, rkoychev commented on src/animals/Giraffe.ts
>      height:number;
not formatted

2024-08-15 09:51 UTC, rkoychev commented on src/hierarchy/Mammal.ts
> +    generateRandomHeight(lowBound:number, highBound:number){
format code

2024-08-15 11:04 UTC, merged